set(PX_RGB
	nmap_default
	nmap_asphalt027c
	# nmap_bong
	nmap_books0
	nmap_br_wall0
	nmap_bricks
	nmap_bricks1
	nmap_capsulegun
	nmap_checkerfloor
	nmap_chud
	nmap_clock0
	nmap_crt
	nmap_door0
	nmap_door1
	nmap_dplate006c
	nmap_fabric0020
	nmap_fabric025
	nmap_fabric048
	nmap_fireball
	nmap_grass1
	nmap_keyboard
	nmap_light0
	nmap_light1
	nmap_m203
	nmap_mp5
	nmap_metal0076
	nmap_metal0068
	nmap_metal022
	nmap_metalplate0
	nmap_metalplates001
	nmap_metalplates009
	nmap_monitor0
	# nmap_mule
	nmap_mutt
	nmap_nameplate0
	nmap_noise0
	nmap_noise1
	nmap_obook0
	nmap_paintmetal005
	nmap_panel0
	nmap_pavingstone128
	nmap_planks014
	nmap_plastic0018
	# nmap_quadbot_base
	# nmap_quadbot_details
	# nmap_quadbot_leg
	nmap_rack_front
	nmap_rocket
	nmap_sand0
	nmap_scifi0
	nmap_scratch0
	nmap_shotgun
	nmap_smg
	nmap_signcattle
	nmap_signvacay
	nmap_soy0
	nmap_tactile003
	nmap_thatch0
	nmap_tiles
	nmap_tiles0059
	nmap_tiles0094
	nmap_tiles129b
	nmap_trashbin0_fr
	nmap_trashbin0_side
	nmap_trippy0
	nmap_waves0
	nmap_wires0
	nmap_wood066
	)

set(PX_GRAY
	tex_asphalt027c
	# tex_bong
	tex_books0
	tex_br_wall0
	tex_bricks
	tex_bricks1
	tex_capsulegun
	tex_checkerfloor
	tex_chud
	tex_chudshirt
	tex_clock0
	tex_door0
	tex_door1
	tex_dplate006c
	tex_fabric0020
	tex_fabric025
	tex_fabric048
	tex_grass1
	tex_gray
	tex_gray_lt
	tex_keyboard
	tex_litme0
	tex_m203
	tex_mp5
	tex_metal0068
	tex_metal0076
	tex_metal022
	tex_metalplate0
	tex_metalplates001
	tex_metalplates009
	tex_nameplate0
	tex_noise0
	tex_paintmetal005
	tex_panel0
	tex_pavingstone128
	tex_planks014
	tex_plastic0018
	tex_sand0
	tex_scifi0
	tex_scratch0
	tex_shotgun
	tex_signvacay
	tex_smg
	tex_soy0
	tex_tactile003
	tex_thatch0
	tex_tiles0059
	tex_tiles0094
	tex_tiles129b
	tex_trashbin0_fr
	tex_trashbin0_side
	tex_trippy0
	tex_troon
	tex_water0
	tex_waves0
	tex_white
	tex_wires0
	tex_wood066
	)
set(PX_GRAY_ALT
	tex_animutv0
	tex_animutv1
	tex_animutv2
	tex_animutv3
	tex_console0_0
	tex_console0_1
	tex_console0_2
	tex_console0_3
	tex_console0_4
	tex_console0_5
	tex_error0_0
	tex_error0_1
	tex_error0_2
	tex_error0_3
	tex_error0_4
	tex_error0_5
	tex_error0_6
	tex_error0_7
	tex_error0_8
	tex_error0_9
	tex_error0_10
	tex_error0_11
	tex_error0_12
	tex_error0_13
	tex_error0_14
	tex_error0_15
	tex_lain0_0
	tex_lain0_1
	tex_lain0_2
	tex_lain0_3
	tex_lain0_4
	tex_lain0_5
	# tex_mule
	tex_monitor0
	tex_nosleep0
	tex_nosleep1
	tex_nosleep2
	tex_nosleep3
	tex_nosleep4
	tex_nosleep5
	tex_nosleep6
	tex_nosleep7
	tex_nosleep8
	tex_nosleep9
	tex_obook0
	tex_pixelmutt0
	tex_pixelmutt1
	tex_pixelmutt2
	tex_pixelmutt3
	tex_pixelmutt4
	tex_pixelmutt5
	tex_pixelmutt6
	tex_pixelmutt7
	tex_pixelmutt8
	tex_pixelmutt9
	tex_pixelmutt10
	tex_pixelmutt11
	tex_pixelmutt12
	tex_pixelmutt13
	tex_pixelmutt14
	tex_pixelmutt15
	tex_pixelmutt16
	tex_pixelmutt17
	tex_pixelmutt18
	tex_pixelmutt19
	tex_pixelmutt20
	# tex_quadbot_base
	# tex_quadbot_details
	# tex_quadbot_leg
	tex_scum_wiggler0
	tex_scum_wiggler1
	tex_scum_wiggler2
	tex_scum_wiggler3
	tex_scum_wiggler4
	tex_signcattle
	tex_fireball
	tex_light0
	tex_light1
	tex_mutt
	tex_rack_front
	tex_rocket
	tex_white_alt
	)

set(PX_PAL
	checkbox-ticked
	checkbox-unticked
	chudsvacation
	cursor
	cyberchud_title
	enter-key0
	enter-key1
	sliderbar
	)
